headless: false
num_envs: 4
env_spacing: 2.5
robot_name: hummingbird
goal: [180, 0, 0, 14.0479206009] # 7.02396030045
# roll[dps], pitch[dps], yaw[dps], z[force]
# hummingbird_mass = 0.7160
# gravity = 9.8100004196167

viewer:
  resolution: [960, 720]
  eye: [8, 0., 6.]
  lookat: [0., 0., 1.]

sim:
  _target_: isaaclab.sim.SimulationCfg

  physics_prim_path: /physicsScene
  dt: 0.016129032258064516
  enable_scene_query_support: true
  use_fabric: true
  disable_contact_processing: true
  device: cuda:0
  physx:
    _target_: isaaclab.sim.PhysxCfg
    solver_type: 1
    min_position_iteration_count: 1
    max_position_iteration_count: 255
    min_velocity_iteration_count: 0
    max_velocity_iteration_count: 255
    enable_ccd: false
    enable_stabilization: true
    enable_enhanced_determinism: false
    bounce_threshold_velocity: 0.5
    friction_offset_threshold: 0.04
    friction_correlation_distance: 0.025
    gpu_max_rigid_contact_count: 2097152
    gpu_max_rigid_patch_count: 2097152
    gpu_found_lost_pairs_capacity: 1048576
    gpu_found_lost_aggregate_pairs_capacity: 33554432
    gpu_total_aggregate_pairs_capacity: 524288
    gpu_collision_stack_size: 33554432
    gpu_heap_capacity: 16777216
    gpu_temp_buffer_capacity: 16777216
    gpu_max_num_partitions: 8
    gpu_max_soft_body_contacts: 1048576
    gpu_max_particle_contacts: 1048576

task:
  _target_: omni_drones.envs.isaac_env.TaskCfg
  max_episode_length: 200

  actions:
    - key: [agents, action]
      items:
        RateController:
          asset_name: drone
          inertia: [0.007, 0.007, 0.012]
          ang_rate_gain: [0.1, 0.1, 0.025]
